version: "3"
services:
  redis_pubsub:
    build:
      context: .
      dockerfile: Dockerfile
    image: allocation-image
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_password=mysecretpassword
      - REDIS_HOST=redis
    volumes:
      - ./src:/src
      - ./tests:/tests
    entrypoint:
      - python
      - /src/allocation/entrypoints/redis_eventconsumer.py

  api:
    image: allocation-image
    depends_on:
      - redis_pubsub
    environment:
      - DB_HOST=postgres
      - DB_password=mysecretpassword
      - API_HOST=api
      - REDIS_HOST=redis
    volumes:
      - ./src:/src
      - ./tests:/tests
    entrypoint:
      - uvicorn
      - allocation.entrypoints.api:app
      - --host=0.0.0.0
      - --port=80
    ports:
      - "5000:80"



  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=allocation
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"


