version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - API_HOST=app
      - DB_HOST=postgres
      - DB_password=mysecretpassword
    volumes:
      - ./src:/src
      - ./tests:/tests
    ports:
      - "5000:80"
    networks:
      - common-net
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=allocation
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - common-net

networks:
  common-net: {}