name: Docker Image CI

on:
  push:
    branches: [ "AVakiliT-patch-1" ]
  pull_request:
    branches: [ "AVakiliT-patch-1" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: all
      run: make all
